# -*- coding: utf-8 -*-
"""collab1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2L3X_Fl0FZrcXJ23xg4Uj5qpnLkkf5s
"""

mylist=[1,2,3]
print(mylist)